### ISSUE TITLE
GetGraphemes for కృష్ణ should return కృ and ష్ణ

### ISSUE THREAD

**Issue by kotpal** [ufcpp/GraphemeSplitter#3]
But instead it is returning కృ, ష్ and ణ - which is incorrect.

If you do cursor left or cursor right around కృష్ణ, you can see that there are only 2 graphemes in that string.

**Comment by ufcpp** [comment]
I thought I implemented according to Unicode standard 10.0. Is this my implementation bug? or Unicode specification bug? If latter, I can do nothing.

**Comment by ufcpp** [comment]
If this was an spec bug of Unicode 10.0 and fixed in Unicode 11.0, I may consider updating.

**Comment by kotpal** [comment]
I think there is more to graphemes and character clusters than what is there in the Unicode standard. 

Microsoft has Uniscribe - which is their shaping engine - but has a few functions that gives character break (or cursor stop) positions within a string. That information is more helpful because it returns the indices to begin and end of the character cluster. 

As an example, GetGraphemes on "కృష్ణస్త్రీఙ్ఞష్ణ" will return an array: కృ, ష్, ణ, స్, త్, రీ, ఙ్, ఞ, ష్, ణ. This information is not useful because as an example, స్, త్, రీ is not really helpful. Those 3 characters make the grapheme: స్త్రీ (meaning woman)

Whereas, Uniscribe's ScriptBreak will return the correct information (indices) that allows us to generate a string array that looks like: కృ, ష్ణ, స్త్రీ, ఙ్ఞ, ష్ణ

So there are essentially 5 clusters of characters - which is what I was trying to get.

**Comment by ufcpp** [comment]
I never implement non-standard spec.

**Comment by kotpal** [comment]
Totally understand - but GetGraphemes as it stands is not of much use - especially for complex scripts. It is up to you to fix it or not, but wanted to bring this to your attention. 

Uniscribe is providing additional information that is not captured in the Unicode spec - especially for complex scripts.

**Comment by ufcpp** [comment]
so please feedback to Uncode consortium.

**Comment by kotpal** [comment]
This is not in the scope of Unicode spec or consortium, unfortunately.

**Comment by ufcpp** [comment]
Unicode 9.0 defines `Prepend` as 

Indic_Syllabic_Category = Consonant_Preceding_Repha, or
Indic_Syllabic_Category = Consonant_Prefixed

Is ణ `Consonant_Prefixed`?
